version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mysql
    ports:
      - "4000:4000"
    networks:
      - backend

  mysql:
    image: mysql:8.0.26
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel8
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend
    expose:
      - "3306"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    networks:
      - backend

  composer:
    image: composer:2.0.14
    container_name: mycomposer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['composer']
    depends_on:
      - php
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge